import {fieldType, formatTime} from "types";

const {INPUT, RADIO_VN, DATE, COMBO_BOX} = fieldType;
const css = {xs: 24, sm: 24, md: 24, lg: 12, xl: 12};
const fields: any[] = [
  {
    key: "orderNumber",
    name: "orderNumber",
    label: "Số lệnh",
    type: INPUT,
    css: css,
  },
  {
    key: "commandDateCreated",
    name: "commandDateCreated",
    label: "Ngày trên phiếu",
    type: DATE,
    css: css,
    disableDate: false,
  },
  {
    key: "baseFromDate",
    name: "baseFromDate",
    label: "Căn cứ kế hoạch từ ngày",
    type: DATE,
    css: css,
    disableDate: false,
  },
  {
    key: "baseToDate",
    name: "baseToDate",
    label: "Căn cứ kế hoạch đến ngày",
    type: DATE,
    css: css,
    disableDate: false,
  },
  {
    key: "mission",
    name: "mission",
    label: "Nhiệm vụ",
    type: INPUT,
    css: css,
  },
  {
    key: "vehicle",
    name: "vehicle",
    label: "Xe",
    type: COMBO_BOX,
    css: css,
  },
  // {
  //   key: "label",
  //   name: "label",
  //   label: "Nhãn hiệu xe",
  //   type: INPUT,
  //   css: css,
  // },
  // {
  //   key: "license",
  //   name: "license",
  //   label: "Biển số",
  //   type: INPUT,
  //   css: css,
  // },

  {
    key: "fromLocationGo",
    name: "fromLocationGo",
    label: "Đi từ",
    type: INPUT,
    css: css,
  },
  {
    key: "toLocationGo",
    name: "toLocationGo",
    label: "Đi đến",
    type: INPUT,
    css: css,
  },
  {
    key: "distanceGo",
    name: "distanceGo",
    label: "Quãng đường đi",
    type: INPUT,
    css: css,
  },
  {
    key: "unitWorkGo",
    name: "unitWorkGo",
    label: "Đơn vị sử dụng đi",
    type: COMBO_BOX,
    css: css,
  },
  {
    key: "quantityGo",
    name: "quantityGo",
    label: "Số lượng đi",
    type: INPUT,
    css: css,
  },
  {
    key: "numberTripGo",
    name: "numberTripGo",
    label: "Số chuyến đi",
    type: INPUT,
    css: css,
  },
  {
    key: "fromLocationBack",
    name: "fromLocationBack",
    label: "Về từ",
    type: INPUT,
    css: css,
  },
  {
    key: "toLocationBack",
    name: "toLocationBack",
    label: "Về đến",
    type: INPUT,
    css: css,
  },
  {
    key: "distanceBack",
    name: "distanceBack",
    label: "Quãng đường về",
    type: INPUT,
    css: css,
  },
  {
    key: "unitWorkBack",
    name: "unitWorkBack",
    label: "Đơn vị sử dụng về",
    type: COMBO_BOX,
    css: css,
  },
  {
    key: "quantityBack",
    name: "quantityBack",
    label: "Số lượng về",
    type: INPUT,
    css: css,
  },
  {
    key: "numberTripBack",
    name: "numberTripBack",
    label: "Số chuyến về",
    type: INPUT,
    css: css,
  },
  {
    key: "extra",
    name: "extra",
    label: "Chở kết hợp",
    type: INPUT,
    css: css,
  },
  {
    key: "performDateTime",
    name: "performDateTime",
    label: "Thời gian có mặt",
    type: DATE,
    css: css,
    disableDate: false,
    optionsTime: {format: formatTime.dateTime},
  },
  {
    key: "state",
    name: "state",
    label: "Lệnh đột xuất?",
    type: RADIO_VN,
    css: css,
    defaultValue: 0,
    options: [
      {value: 0, label: "Không"},
      {value: 1, label: "Có"},
    ],
  },
];
export {fields};
